### ISSUE TITLE
Windows Build Instructions

### ISSUE THREAD

**Issue by Nolram12345** [apistol78/traktor#2]
Hi! This engine looks incredible, and I'd love to try it out!
However, I'm having some trouble figuring out how to build it on Windows. Linux instructions are provided in the readme, and I have also tried to use the provided batch files to build it myself, but I'm not sure if I am doing it right. In what capacity is Windows even supported?

Thank you!

**Comment by Nolram12345** [comment]
The key issue is that a lot of the "extern" projects don't build, due to not being able to find the dependency files. How does one install these on windows?

**Comment by apistol78** [comment]
Hi! Thanks!
I've added some instructions on how to build Windows version. I do build Windows regularly but havn't got around to setting up github actions yet.
I hope it helps, let me know if there are any issues!
Cheers!

**Comment by Nolram12345** [comment]
I'll try it out and then see if it works!

**Comment by Nolram12345** [comment]
Tried it out - some things don't quite work.
The FBX SDK does get installed, but doesn't get linked to the projects (neither include directory nor library files).

There's also this weird syntax error when building ReleaseShared (which seems to be necessary to get the editor to build?):
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2059	syntax error: '}'	Extern.theora	traktor\3rdp\theora\lib\encoder_disabled.c	20	
```

ftgzip from Freetype also fails to open zlib - it seems it's looking for system zlib and not using it's own provided zlib (the macro `FT_CONFIG_OPTION_SYSTEM_ZLIB` seems to be true).

There may be more, but that's what I've found for now.

**Comment by apistol78** [comment]
Thanks for trying!
I've pushed a fix for FBX and Theora dependencies.
Regarding freetype I'm not sure since I'm able to do a complete rebuild on a clean repo now without errors...
You could give it a go again, but first ensure to wipe the 3rdp folder and re-run the build steps.

**Comment by Nolram12345** [comment]
Tried it again - almost everything works now, but the issue with the zlib install that freetype is looking for persists.
This is caused because the option to use system-level zlib (which seems to be more common on Linux/Unix OSs) is enabled (line 277, ftoption.h). Commenting that define out makes it work, but then it complains that it can't find png.h (which seems to be libpng), for which it too seems to search on a system level. There is an option to disable that too (which is probably not ideal either), so I did, but then the linker throws this error:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol FT_Stream_OpenBzip2 referenced in function PCF_Face_Init	Traktor.Spark.Editor	traktor\build\win64\Traktor.Spark.Editor\Extern.freetype.lib(pcf.obj)	1	
`
However, the editor still builds and launches correctly.

**Comment by Nolram12345** [comment]
I also tried to use your Kobolt game that you have up to test out the editor - managed to open the workspace just fine, but actually loading a scene doesn't seem to work - I just get an empty scene, it seems assets don't load. Entities also have no components on them for some reason? Maybe I opened the wrong thing?
![image](https://github.com/apistol78/traktor/assets/37701550/8b8157ee-8d1c-42d5-bf34-9ede35069593)

**Comment by apistol78** [comment]
This is weird, in my include/freetype/config/ftoption.h file at 277 there is only a disabled FT_CONFIG_OPTION_USE_PNG...
Also the FT_CONFIG_OPTION_SYSTEM_ZLIB is disabled in my file...
Where is your ftoption.h located? It should be in 3rdp/freetype/include/freetype/config/

Also since Traktor's freetype is built using our own custom build tool then there is no autogenerated configuration file when building freetype through Traktor solution.

Regarding Kobolt it's difficult to guess since there is no log window visible.
Log files from the editor are saved in C:\Users\<username>\AppData\Local\Traktor\Editor\Logs.

**Comment by Nolram12345** [comment]
> Also the FT_CONFIG_OPTION_SYSTEM_ZLIB is disabled in my file...
Where is your ftoption.h located? It should be in 3rdp/freetype/include/freetype/config/

Yes, that file does exist there - however, the one ACTUALLY used in the build is in traktor\3rdp\freetype\build\include\freetype\config - which is odd.

**Comment by Nolram12345** [comment]
Also, I re-built the whole engine, cloned Kobolt again, and when I try to open the "Scene" scene, the editor hangs.
This is the log:
[Editor_2.log](https://github.com/apistol78/traktor/files/13315373/Editor_2.log)

**Comment by apistol78** [comment]
I'm absolutely not sure what's going on, after syncing 3rdp the folder **traktor\3rdp\freetype\build** is empty and there are never any files in that folder after building Traktor either...
There is one other ftoptions.h in **traktor\3rdp\freetype\devel** but that's not used.

About issues with Kobolt, I've totally forgot to mention that you need to have Blender installed, and the path to Blender.exe need to be in the PATH environment... Sorry about that :|
The reason is that Traktor are using Blender to be able to import .blend files to the engine.

**Comment by Nolram12345** [comment]
> I'm absolutely not sure what's going on, after syncing 3rdp the folder **traktor\3rdp\freetype\build** is empty and there are never any files in that folder after building Traktor either... There is one other ftoptions.h in **traktor\3rdp\freetype\devel** but that's not used.

That's quite odd. I've thus far always made a clean re-clone of the whole repository and built from scratch, and the result seems to always be the same. I can however as a workaround hopefully just copy the correct options to the path where it's picking it up from

> About issues with Kobolt, I've totally forgot to mention that you need to have Blender installed, and the path to Blender.exe need to be in the PATH environment... Sorry about that :| The reason is that Traktor are using Blender to be able to import .blend files to the engine.

Thats good to know! I have Blender installed, but not on path. I'll do that then!

**Comment by Nolram12345** [comment]
Added Blender to PATH and tried it out again - the scene now loads correctly! Exploring the engine is quite exciting, but I think a couple instructions for a couple basic things would be super useful, like explaining the basic workspace layout and how to build and run a game. And of course, feature documentation would be great too, but is obviously a lot of effort.
I'm especially curious on how the lightmapping and such is used, and what the basic flow of importing an asset is like.

**Comment by apistol78** [comment]
Great news! :)
I agree that Traktor lacks documentation, even the most basic one, and it has been on my mind for a long time.
I'm really not at all good at writing tutorials or documentation so all my attempt has just been half baked at best.
But I think that, since I've put Traktor up on github, it's probably time to do another attempt :)
